# Generated by Django 2.1.dev20180102010948 on 2018-01-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
